/*
 * Copyright (c) 2023, TopS BI LLC. All rights reserved.
 * http://www.topsbi.ru
 */

/*
 * Copyright (c) 2023, TopS BI LLC. All rights reserved.
 * http://www.topsbi.ru
 */

package az.namazov.bookkeeping.enums.operation;

import java.util.List;
import java.util.Map;

import az.namazov.bookkeeping.enums.bank.tinkoff.TinkoffCategory;
import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum Category {

    CAR_SHARING(Map.of("Тиньков", List.of(TinkoffCategory.CAR_SHARING.name()),
                "Банк Развитие", List.of("sds"),
                "Альфа-Банк", List.of("sdsd"))),
    COSMETICS(Map.of("Тиньков", List.of(TinkoffCategory.COSMETICS.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    LOCAL_TRANSPORT(Map.of("Тиньков", List.of(TinkoffCategory.LOCAL_TRANSPORT.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    EDUCATION(Map.of("Тиньков", List.of(TinkoffCategory.EDUCATION.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    TOLL_ROADS(Map.of("Тиньков", List.of(TinkoffCategory.TOLL_ROADS.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    TAXI(Map.of("Тиньков", List.of(TinkoffCategory.TAXI.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    ELECTRONICS_AND_TECHNOLOGY(Map.of("Тиньков", List.of(TinkoffCategory.ELECTRONICS_AND_TECHNOLOGY.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    STATIONERY(Map.of("Тиньков", List.of(TinkoffCategory.STATIONERY.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    CHILDREN_GOODS(Map.of("Тиньков", List.of(TinkoffCategory.CHILDREN_GOODS.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    NO_CASHBACK(Map.of("Тиньков", List.of(TinkoffCategory.NO_CASHBACK.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    FLIGHTS(Map.of("Тиньков", List.of(TinkoffCategory.FLIGHTS.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    AUTO_SERVICE(Map.of("Тиньков", List.of(TinkoffCategory.AUTO_SERVICE.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    RENT_CAR(Map.of("Тиньков", List.of(TinkoffCategory.RENT_CAR.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    PHARMACIES(Map.of("Тиньков", List.of(TinkoffCategory.PHARMACIES.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    HOUSE_RENOVATION(Map.of("Тиньков", List.of(TinkoffCategory.HOUSE_RENOVATION.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    TRAIN_TICKETS(Map.of("Тиньков", List.of(TinkoffCategory.TRAIN_TICKETS.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    ANIMAL(Map.of("Тиньков", List.of(TinkoffCategory.ANIMAL.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    ART(Map.of("Тиньков", List.of(TinkoffCategory.ART.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    CINEMA(Map.of("Тиньков", List.of(TinkoffCategory.CINEMA.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    BOOKS(Map.of("Тиньков", List.of(TinkoffCategory.BOOKS.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    PHOTO_VIDEO(Map.of("Тиньков", List.of(TinkoffCategory.PHOTO_VIDEO.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    BEAUTY(Map.of("Тиньков", List.of(TinkoffCategory.BEAUTY.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    MUSIC(Map.of("Тиньков", List.of(TinkoffCategory.MUSIC.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    CLOTHES_SHOES_JEWELRY_WATCHES(Map.of("Тиньков", List.of(TinkoffCategory.CLOTHES_SHOES_JEWELRY_WATCHES.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    ENTERTAINMENT(Map.of("Тиньков", List.of(TinkoffCategory.ENTERTAINMENT.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    RESTAURANTS(Map.of("Тиньков", List.of(TinkoffCategory.RESTAURANTS.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    SPORTING_GOODS(Map.of("Тиньков", List.of(TinkoffCategory.SPORTING_GOODS.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    SOUVENIRS(Map.of("Тиньков", List.of(TinkoffCategory.SOUVENIRS.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    TRANSPORT(Map.of("Тиньков", List.of(TinkoffCategory.TRANSPORT.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    FAST_FOOD(Map.of("Тиньков", List.of(TinkoffCategory.FAST_FOOD.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    FUEL(Map.of("Тиньков", List.of(TinkoffCategory.FUEL.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    SUPER_MARKET(Map.of("Тиньков", List.of(TinkoffCategory.SUPER_MARKET.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    DUTY_FREE(Map.of("Тиньков", List.of(TinkoffCategory.DUTY_FREE.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    DIGITAL_GOODS(Map.of("Тиньков", List.of(TinkoffCategory.DIGITAL_GOODS.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    VARIOUS_GOODS(Map.of("Тиньков", List.of(TinkoffCategory.VARIOUS_GOODS.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    SERVICE(Map.of("Тиньков", List.of(TinkoffCategory.SERVICE.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    MOBILE_CONNECTION(Map.of("Тиньков", List.of(TinkoffCategory.MOBILE_CONNECTION.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    REPLENISHMENT(Map.of("Тиньков", List.of(TinkoffCategory.REPLENISHMENT.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    PERCENT(Map.of("Тиньков", List.of(TinkoffCategory.PERCENT.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    HOME_AND_REPAIR(Map.of("Тиньков", List.of(TinkoffCategory.HOME_AND_REPAIR.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    TRANSFER(Map.of("Тиньков", List.of(TinkoffCategory.TRANSFER.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    BONUS(Map.of("Тиньков", List.of(TinkoffCategory.BONUS.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    ANOTHER(Map.of("Тиньков", List.of(TinkoffCategory.ANOTHER.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    GKH(Map.of("Тиньков", List.of(TinkoffCategory.GKH.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    ONLINE_CINEMA(Map.of("Тиньков", List.of(TinkoffCategory.ONLINE_CINEMA.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    CLOSES_AND_SHOES(Map.of("Тиньков", List.of(TinkoffCategory.CLOSES_AND_SHOES.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    REFILLS(Map.of("Тиньков", List.of(TinkoffCategory.REFILLS.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    BANK_SERVICE(Map.of("Тиньков", List.of(TinkoffCategory.BANK_SERVICE.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    MEDICINE(Map.of("Тиньков", List.of(TinkoffCategory.MEDICINE.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd"))),
    FLOWERS(Map.of("Тиньков", List.of(TinkoffCategory.FLOWERS.name()),
            "Банк Развитие", List.of("sds"),
            "Альфа-Банк", List.of("sdsd")));

    private final Map<String, List<String>> compareList;
}
